version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www
      - ./docker/logs:/var/log/nginx
    links:
      - php
  php:
    build: ./docker/images/php
    links:
      - mysql
    volumes:
      - ./:/var/www
      - ./docker/images/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80